---
version: '3.7'
services:
  nginx:
    build: services/nginx
    links:
      - php
    networks:
      - flarum
    volumes:
      - ../:/var/www/:cached
    ports:
      - "80:80"

  php:
    build:
      context: services/php-fpm
    user: ${UID}:${UID}
    working_dir: /var/www
    env_file:
      - ./.docker.conf
    links:
      - mysql
      - mailtrap
      - ldap
    networks:
      - flarum
    volumes:
      - ../:/var/www:cached
    expose:
      - "9000"

  mysql:
    image: mariadb:10.3
    networks:
      - flarum
    expose:
      - "3306"
    env_file:
      - ./.docker.conf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql
    networks:
      - flarum
    env_file:
      - ./.docker.conf

  mailtrap:
    image: eaudeweb/mailtrap
    networks:
      - flarum
    expose:
      - "25"
    ports:
      - 8001:80

  ldap:
    image: osixia/openldap
    networks:
      - flarum
    expose:
      - "389"
      - "636"
    ports:
      - "389:389"
    environment:
      LDAP_ORGANISATION: "Flarum organisation"
      LDAP_DOMAIN: "flarum.com"
      LDAP_ADMIN_PASSWORD: "flarum"
      # Default DN = cn=admin,dc=flarum,dc=com

  ldapadmin:
    image: osixia/phpldapadmin
    networks:
      - flarum
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    links:
      - "ldap"

networks:
  flarum:
